name: Feature Request
description: Suggest an idea or improvement for this project
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a feature. Please describe your idea so we can evaluate and prioritize it.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: A clear description of the problem this feature would solve.
      placeholder: "I'm frustrated when..."
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: Your idea for how to solve it.
      placeholder: Describe your proposed solution...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions or workarounds you've considered.
      placeholder: Describe alternatives...
    validations:
      required: false

  - type: dropdown
    id: affected-layer
    attributes:
      label: Affected Layer
      description: Which layer of the architecture would this feature impact?
      multiple: true
      options:
        - "Domain"
        - "Application"
        - "Infrastructure"
        - "WebApi"
        - "WalletApp (Blazor)"
        - "AppHost (Aspire)"
        - "ServiceDefaults"
        - "Tests"
        - "Build / CI"
        - "Documentation"
    validations:
      required: false

  - type: dropdown
    id: scope
    attributes:
      label: Scope
      description: How large is this feature?
      options:
        - "Small — minor tweak or addition"
        - "Medium — new capability within existing layer"
        - "Large — cross-cutting or architectural change"
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other context, mockups, code examples, or references.
      placeholder: Add any other context here...
    validations:
      required: false
